name: Build Storm and run unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java & Maven
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 11
          java-distribution: 'temurin'
          maven-version: 3.6.3

      - name: Configure Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.2

      - name: Configure NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 8.9.3

      - name: Configure Python (v. 3.x)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install libssl-dev
        run: sudo apt-get install -y libssl-dev

      - name: Install Mock Library with pip
        run: pip install mock

      - name: Verify storm
        run: mvn clean verify --batch-mode
